### ISSUE TITLE
Triggers Jailbreak Detection on 12.4

### ISSUE THREAD

**Issue by civicsr2cool** [BrandonPlank/rootlessJB4#19]
I have never installed a tweak, saily, filza, or anything else. Simply tapping jailbreak and respringing triggers the detection. iPhone X 12.4 with latest rootless release, all previous releases also triggered it but not on my previous 11.1.2 rootlessjb by Jake James.

**Comment by yonigold1** [comment]
does snapchat see it as well?

**Comment by civicsr2cool** [comment]
I read a comment on Reddit that it does. I’m definitely not testing that one myself though!

**Comment by brandonplank** [comment]
Have you ever used unc0ver? You might need to restore your rootFS first before trying rootlessJB. As of now, i have not had any detection issues.

**Comment by civicsr2cool** [comment]
Never ran uncover except to export tfp0/ssh only on earlier Rootlessjb4 versions to get a11 working. Rootfs is restored, phone started as a12.4 dfu restore. On reddit it seems everyone has the detection issues? I have used filzaescaped to do system mods such as changing sounds/boot logo/etc, could that be an issue? 

I only get detected while in jailbreak mode, after a reboot all is fine. Zero tweaks installed, no package installers either, not even filza.

**Comment by huyle0406** [comment]
Hello, I tried your rootlessjb but the detection still triggered in Princess Connect game without any tweak installed. On IOS 11, it is the same problem when i used rootlessjb3 by tigisoftware. It was fine before version 3.2.3 in rootlessjb3 but after merged dpkg the game triggered the detection. Could you elaborate this problem for me?
