### ISSUE TITLE
doesn't work on iPhone x

### ISSUE THREAD

**Issue by asadboi123** [BrandonPlank/rootlessJB4#2]
I instantly get "Got Root" but nothing happens, no Filza no iSupersu, can't even ssh.

**Comment by SarahH12099** [comment]
I am having the same problem, iPhone 8 Plus, freshly restored too. Installed the ipa using a paid signing service (ipastore).

Edit: I also tried older versions and they never worked either.

**Comment by HomemadeToast57** [comment]
Also having this problem
