### ISSUE TITLE
Cant log in ReProvision

### ISSUE THREAD

**Issue by zunda-pixel** [BrandonPlank/rootlessJB4#22]
ReProvision crashs when "Checking Device Status" Step  is loaded.
iPhone 6s iOS 12.4

**Comment by zxsleebu** [comment]
Same. iPhone 6, iOS 12.4. Did you found a solution?

**Comment by zunda-pixel** [comment]
no

**Comment by zxsleebu** [comment]
I checked his code and he forgot to add ReProvision daemon "reprovisiond" to tweaksupport archive, that's using by tweaks. If I manually adding this daemon there, I can login, but apps can't be signed. When process coming to 30% it jumping to 90% and "successfully" ends — app isn't signed. Also when i enable debug alerts they doesn't showing up :/. Maybe ReProvision will work if I'll run old version of app, but i can't find that

**Comment by brandonplank** [comment]
The daemon is manually moved to the destination via code in the app. take a look at the code starting here https://github.com/BrandonPlank/rootlessJB4/blob/master/rootlessjb/rootlessJB4/ViewControllers/MainController/ViewController.m#L547

It will help if you uninstall, then re-jailbreak!
