### ISSUE TITLE
Options cut off on small screens

### ISSUE THREAD

**Issue by easrng** [BrandonPlank/rootlessJB4#35]
On my iPhone 5s, some options are cut off. I can't provide a screenshot right now because I'm in a respring loop.

**Comment by KJThaDon** [comment]
Same here...

**Comment by LegendOfRiots** [comment]
![35E11E25-367F-4319-B664-EE7AC27166B0](https://user-images.githubusercontent.com/44318593/88190210-ec692900-cc31-11ea-8eed-91824e8f00ff.png)

**Comment by brandonplank** [comment]
I am fixing the issue as we speak
