### ISSUE TITLE
Sudden Reboot

### ISSUE THREAD

**Issue by ghost** [BrandonPlank/rootlessJB4#39]
iPhone 6 ios 12.4.8
Sudden reboot on any apps randomly after jailbreak.
I use Altstore to sideload both rootlessjb and saily
Thanks

**Comment by TheFine** [comment]
Did the landlord solve the automatic restart

**Comment by TheFine** [comment]
Lóuzhǔ jiějué zìdòng chóngqǐle ma

**Comment by TheFine** [comment]
Landlord solve automatic restart yet
