### ISSUE TITLE
[Fixed]Can't finish [Set platformize!] Step

### ISSUE THREAD

**Issue by zunda-pixel** [BrandonPlank/rootlessJB4#8]
rootlessJB4 Latest IPA Version
iPhone 6s iOS 12.4

1. Tap Jailbreak!
2. Show [Set platformize!]
3. after 5 minutes. still [Set platformize!]

**Comment by aptx17** [comment]
same on 6s -12.0.1, try this https://github.com/Co2333/rootlessJB4

**Comment by mikemike998** [comment]
Same on Iphone 7 IOS 12.4

**Comment by TomerGamerTV** [comment]
same on iphone 6 ios 12.1.4
